name: Receive repository dispatch event

on:
  workflow_dispatch:
  repository_dispatch:
    types: [dispatch-event]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Event received
        run: echo "Event received"
